---
title: "Licenses"
output: github_document # github_document, html_document, pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Written in 2020 by Diana J.R. Lafferty (<dlaffert@nmu.edu>), Paul Q. Sims (<paul.q.sims@gmail.com>), and L. Scott Mills (<scott.mills@mso.umt.edu>)

## Data: CC0 1.0 Universal license

Copyright &copy; 2020 Diana J.R. Lafferty, Paul Q. Sims, and L. Scott Mills

To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.

You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

## Software and code: MIT license

Copyright &copy; 2020 Diana J.R. Lafferty, Paul Q. Sims, and L. Scott Mills

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

## Markdown, rmarkdown, image and pdf media: CC-BY-4.0 license

Copyright &copy; 2020 Diana J.R. Lafferty, Paul Q. Sims, and L. Scott Mills

UNLESS OTHERWISE NOTED, THE CONTENTS OF THIS DIRECTORY ARE LICENSED UNDER </a><br /><a rel="license" href="http://creativecommons.org/licenses/by/4.0/">THE CREATIVE COMMONS ATTRIBUTION 4.0 INTERNATIONAL LICENSE</a>.